base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('store.urls', namespace="store")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

store/urls.py
from django.urls import path 
from .views import (CheckoutView, ItemDetail, HomeView, add_to_cart, 
                    remove_from_cart, OrderSummaryView, remove_single_item_from_cart,
                    PaymentView, AddCouponView, RequestRefundView, CategoryDetail
)
app_name = "store"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("product/<slug>", ItemDetail.as_view(), name="product"),
    path("add-to-cart/<slug>", add_to_cart, name="add-to-cart"),
    path("add-coupon", AddCouponView.as_view(), name="add-coupon"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove-from-cart"),
    path("remove-single-item-from-cart/<slug>", remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path("payment/<payment_option>", PaymentView.as_view(), name="payment"),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('categorydetail/<slug>', CategoryDetail, name='categorydetail')
]

store/models.py
from django.db.models.signals import post_save
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.

# CATEGORY_CHOICES = (
#     ('S', 'Shirt'),
#     ('SW', 'Sport wear'),
#     ('OW', 'Outwear'),
#     ('E', 'ELECTRONICS')
# )

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.title


class Item(models.Model):
    user = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    # category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(upload_to="static/img/products", blank=True, null= True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('store:product', kwargs={'slug': self.slug})

    def get_add_to_cart_url(self):
        return reverse('store:add-to-cart', kwargs={ 'slug': self.slug })

    def get_remove_from_cart_url(self):
        return reverse('store:remove-from-cart', kwargs={ 'slug': self.slug })

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)


    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()

        if self.coupon:
            total -= self.coupon.amount

        return total


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"



# def userprofile_receiver(sender, instance, created, *args, **kwargs):
#     if created:
#         userprofile = UserProfile.objects.create(user=instance)


# post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/all_products.html
{% extends 'base.html' %}


{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <section class="">
          <div class="container px-5 px-lg-5 mt-5">
              <div class="row gx-4 gx-lg-2 row-cols-1 row-cols-md-3 row-cols-xl-4 ">
                {% for item in items %}
                  <div class="col mb-5">
                      <div class="card h-100 border-0 shadow-sm overflow-hidden" style="border-radius: 1rem;">
                          <img class="card-img-top img-fluid" src="{{item.image.url}}" alt="..."  style="height: 10rem; object-fit: contain;"/>
                          <div class="card-body p-4" >
                              <div class="text-center">
                                <span>{{item.category}}</span>
                                <h5>
                                  <strong>
                                    <p href="{{item.get_absolute_url}}" class="text-dark">{{item.title}}
                                      <span class="badge rounded-pill bg-{{item.get_label_display}}">NEW</span>
                                    </p>
                                  </strong>
                                </h5>
                                  <h6 class="font-weight-bold blue-text">
                                    <span>$
                                      {% if item.discount_price %}
                                        {{item.discount_price}}
                                      {% else %}
                                        {{item.price}}
                                      {% endif %}
                                    </span>
                                  </h6>
                              </div>
                          </div>
                          <!-- Product actions-->
                          <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                              <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="{{item.get_absolute_url}}">View Details</a></div>
                          </div>
                      </div>
                  </div>
                {% endfor %}
              </div>
          </div>
      </section>



      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}
      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.72.0">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'custom.css' %}">


</head>

<body class="bg-light">
    {% include 'components/navbar.html' %}

    <div class="">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}

    {% endblock %}
    
    {% include 'components/footer.html' %}
    
    <script src="{% static 'home/js/bootstrap.bundle.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>

    {% block extra_scripts %}
    {% endblock extra_scripts %}

</body>

</html>

templates/category.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}

<section class="container">
  <div class="container px-4 px-lg-5 mt-4">
    <p class="text-center fw-bold fs-3 mb-3">{{ data.title }}</p>
    <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-3">
      {% for item in category %}
        <div class="col mb-5">
                <div class="card h-100 border-0 shadow-sm overflow-hidden" style="border-radius: 1rem;">
                    <img class="card-img-top img-fluid" src="{{item.image.url}}" alt="..."  style="height: 10rem; object-fit: contain;"/>
                    <div class="card-body p-4" >
                        <div class="text-center">
                          <span>{{item.category}}</span>
                          <h5>
                            <strong>
                              <p href="{{item.get_absolute_url}}" class="text-dark">{{item.title}}
                                <span class="badge rounded-pill bg-{{item.get_label_display}}">NEW</span>
                              </p>
                            </strong>
                          </h5>
                            <h6 class="font-weight-bold blue-text">
                              <span>$
                                {% if item.discount_price %}
                                  {{item.discount_price}}
                                {% else %}
                                  {{item.price}}
                                {% endif %}
                              </span>
                            </h6>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto rounded-pill" href="{{item.get_absolute_url}}">View Details</a></div>
                    </div>
                </div>
            </div>
      {% endfor %}
    </div>
  </div>
</section>

{% endblock content %}

templates/checkout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

  <main >
    <div class="container wow fadeIn">
      <h2 class="my-5 h2 text-center">Checkout form</h2>
      <div class="row">
        <div class="col-md-8 mb-4">
          <div class="card">
            <form method="POST" class="card-body">
              {% csrf_token %}

              <h3>Shipping address</h3>

              <div class='hideable_shipping_form'>

                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='shipping_address' name='shipping_address' class='form-control' />
                  <label for="shipping_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='shipping_address2' name='shipping_address2' class='form-control' />
                  <label for="shipping_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.shipping_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>
                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="shipping_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='shipping_zip' name='shipping_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>
                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="same_billing_address" id="same_billing_address">
                  <label class="custom-control-label" for="same_billing_address">Billing address is the same as my shipping address</label>
                </div>
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_shipping" id="set_default_shipping">
                  <label class="custom-control-label" for="set_default_shipping">Save as default shipping address</label>
                </div>

              </div>

              {% if default_shipping_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_shipping" id="use_default_shipping">
                <label class="custom-control-label" for="use_default_shipping">Use default shipping address: {{ default_shipping_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}

              <hr>

              <h3>Billing address</h3>

              <div class='hideable_billing_form'>
                <div class="md-form mb-5">
                  <input type='text' placeholder='1234 Main St' id='billing_address' name='billing_address' class='form-control' />
                  <label for="billing_address" class="">Address</label>
                </div>

                <div class="md-form mb-5">
                  <input type='text' placeholder='Apartment or suite' id='billing_address2' name='billing_address2' class='form-control' />
                  <label for="billing_address2" class="">Address 2 (optional)</label>
                </div>

                <div class="row">
                  <div class="col-lg-4 col-md-12 mb-4">
                    <label for="country">Country</label>
                    {{ form.billing_country }}
                    <div class="invalid-feedback">
                      Please select a valid country.
                    </div>
                  </div>

                  <div class="col-lg-4 col-md-6 mb-4">
                    <label for="billing_zip">Zip</label>
                    <input type='text' placeholder='Zip code' id='billing_zip' name='billing_zip' class='form-control' />
                    <div class="invalid-feedback">
                      Zip code required.
                    </div>
                  </div>

                </div>

                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" name="set_default_billing" id="set_default_billing">
                  <label class="custom-control-label" for="set_default_billing">Save as default billing address</label>
                </div>

              </div>

              {% if default_billing_address %}
              <div class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" name="use_default_billing" id="use_default_billing">
                <label class="custom-control-label" for="use_default_billing">Use default billing address: {{ default_billing_address.street_address|truncatechars:10 }}</label>
              </div>
              {% endif %}
              <hr>

              <h3>Payment option</h3>

              <div class="d-block my-3">
                {% for value, name in form.fields.payment_option.choices %}
                <div class="custom-control custom-radio">
                  <input id="{{ name }}" name="payment_option" value="{{ value }}" type="radio" class="custom-control-input" required>
                  <label class="custom-control-label" for="{{ name }}">{{ name }}</label>
                </div>
                {% endfor %}
              </div>

              <hr class="mb-4">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>

            </form>

          </div>

        </div>

        <div class="col-md-4 mb-4">
          {% include "order_snippet.html" %}
        </div>

      </div>

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}
<script>
    var hideable_shipping_form = $('.hideable_shipping_form');
    var hideable_billing_form = $('.hideable_billing_form');

    var use_default_shipping = document.querySelector("input[name=use_default_shipping]");
    var use_default_billing = document.querySelector("input[name=use_default_billing]");

    use_default_shipping.addEventListener('change', function() {
      if (this.checked) {
        hideable_shipping_form.hide();
      } else {
        hideable_shipping_form.show();
      }
    })

    use_default_billing.addEventListener('change', function() {
      if (this.checked) {
        hideable_billing_form.hide();
      } else {
        hideable_billing_form.show();
      }
    })
</script>
{% endblock extra_scripts %}

templates/landingPage.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
<div class="">
  <h1 class="text-info">Landing Page</h1>
</div>
{% endblock %}

templates/order_snippet.html
<div class="col-md mb-4">

<!-- Heading -->
<h4 class="d-flex justify-content-between align-items-center mb-3">
<span class="text-muted">Your cart</span>
<span class="badge badge-secondary badge-pill">{{order.items.count}}</span>
</h4>

<!-- Cart -->
<ul class="list-group mb-3 z-depth-1">
{% for order_item in order.items.all %}
<li class="list-group-item d-flex justify-content-between lh-condensed">
    <div>
    <h6 class="my-0">{{order_item.quantity}} x {{order_item.item.title}}</h6>
    <small class="text-muted">{{order_item.item.description}} </small>
    </div>
    <span class="text-muted">${{order_item.get_final_price}}</span>
</li>
{% endfor %}
{% if order.coupon %}
<li class="list-group-item d-flex justify-content-between bg-light">
    <div class="text-success">
    <h6 class="my-0">Promo code</h6>
    <small>{{order.coupon.code}}</small>
    </div>
    <span class="text-success">-${{order.coupon.amount}}</span>
</li>
{% endif %}
<li class="list-group-item d-flex justify-content-between">
    <span>Total (USD)</span>
    <strong>${{order.get_total}}</strong>
</li>
</ul>
<!-- Cart -->

{% if DISPLAY_COUPON_FORM %}
<!-- Promo code -->
<form class="card p-2" action="{% url 'store:add-coupon' %}" method="post">
    {% csrf_token %}
    <div class="input-group">
        {{ CouponForm.code }}
        <!-- <input type="text" class="form-control" placeholder="Promo code" aria-label="Recipient's username" aria-describedby="basic-addon2"> -->
        <div class="input-group-append">
        <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
        </div>
    </div>
</form>
<!-- Promo code -->
{% endif %}

</div>

templates/order_summary.html
{% extends 'base.html' %} 

{% block content %}
<!--Main layout-->
<main>
  <div class="container">
    <h2>Order Summary</h2>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Item title</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total Item Price</th>
        </tr>
      </thead>
      <tbody>
        {% for order_item in object.items.all %}
        <tr>
          <th scope="row">{{ forloop.counter }}</th>
          <td>{{order_item.item.title}}</td>
          <td>{{order_item.item.price}} <del>{{order_item.get_total_discount_item_price}}</del> </td>
          <td>
            <a href="{% url 'store:remove-single-item-from-cart' order_item.item.slug %}" style="text-decoration: none; color:black;">
              <i class="bi bi-dash-circle"></i>-
              {{ order_item.quantity }}
            <a href="{% url 'store:add-to-cart' order_item.item.slug %}" style="text-decoration: none; color:black;">
              <i class="bi bi-plus-circle"></i>+
          </td>
          <td>$
            {% if order_item.item.discount_price %}
              {{order_item.get_total_discount_item_price}}
              <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
              {{order_item.get_total_item_price}}
            {% endif %}
            <a style='color: red;' href="{% url 'store:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="5">Your cart is empty</td>
          <td colspan="4">
            <a class="btn btn-info" href="{% url 'store:home' %}"> continue shoping </a>
          </td>
        </tr>
        {% endfor %}

        {% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}
        
        {% if object.get_total %}
        <tr>
          <td colspan=4><b> Order Total</b></td>
          <td><b> ${{object.get_total}} </b></td>
        </tr>
        <tr>
          <td colspan="4">
            <a class="btn btn-info" href="{% url 'store:home' %}"> continue shoping </a>
            <a class="btn btn-warning mx-2" href="{% url 'store:checkout' %}"> Proceed to checkout </a>
          </td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  </div>
</main>
<!--Main layout-->
{% endblock content %}

templates/payment.html
{% extends "base.html" %}

{% block content %}

  <main >
    <div class="container wow fadeIn">

      <h2 class="my-5 h2 text-center">Payment</h2>

      <div class="row">

        <div class="col-md-12 mb-4">
          <div class="card p-3">

            <div class="new-card-form">
              <form action="/payment/stripe" method="post" id="payment-form">
                {% csrf_token %}
                <div class="form-group">
                  <label for="card-element">
                      Credit or debit card
                  </label>
                  <div id="card-element" class="form-control">
                      <!-- A Stripe Element will be inserted here. -->
                  </div>

                  <!-- Used to display Element errors. -->
                  <div id="card-errors" role="alert"></div>
                </div>

                <button class="btn btn-primary">Submit Payment</button>
              </form>
            </div>

          </div>
        </div>


      </div>


        {% include 'order_snippet.html' %}

    </div>
  </main>

{% endblock content %}

{% block extra_scripts %}

<script src="https://js.stripe.com/v3/"></script>
<script>
(function ($) {
    // Set your publishable key: remember to change this to your live publishable key in production
    // See your keys here: https://dashboard.stripe.com/account/apikeys
    var stripe = Stripe('{{STRIPE_PUBLIC_KEY}}');
    var elements = stripe.elements();

    // Custom styling can be passed to options when creating an Element.
    var style = {
      base: {
          // Add your base input styles here. For example:
        color: '#32325d',
        fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
        fontSmoothing: 'antialiased',
        fontSize: '16px',
        '::placeholder': {
          color: '#aab7c4'
        }
      },
    invalid: {
      color: '#fa755a',
      iconColor: '#fa755a'
    }
  };

    // Create an instance of the card Element.
    var card = elements.create('card', {style: style});

    // Add an instance of the card Element into the `card-element` <div>.
    card.mount('#card-element');

    // Handle real-time validation errors from the card Element.
    card.addEventListener('change', function(event) {
      var displayError = document.getElementById('card-errors');
      if (event.error) {
        displayError.textContent = event.error.message;
      } else {
        displayError.textContent = '';
      }
    });


    // Create a token or display an error when the form is submitted.
    var form = document.getElementById('payment-form');
    form.addEventListener('submit', function(event) {
      event.preventDefault();

      stripe.createToken(card).then(function(result) {
        if (result.error) {
          // Inform the customer that there was an error.
          var errorElement = document.getElementById('card-errors');
          errorElement.textContent = result.error.message;
        } else {
          // Send the token to your server.
          stripeTokenHandler(result.token);
        }
      });
    });

    function stripeTokenHandler(token) {
      // Insert the token ID into the form so it gets submitted to the server
      var form = document.getElementById('payment-form');
      var hiddenInput = document.createElement('input');
      hiddenInput.setAttribute('type', 'hidden');
      hiddenInput.setAttribute('name', 'stripeToken');
      hiddenInput.setAttribute('value', token.id);
      form.appendChild(hiddenInput);

      // Submit the form
      form.submit();
    }

})(jQuery);
</script>

{% endblock extra_scripts %}

templates/product.html
{% extends 'base.html' %}


{% block content %}
    <div class="container my-3">

      <div class="row">

        <div class="col-md-6 mb-4 shadow-sm" >
          <img src="{{object.image.url}}" class="img-fluid" alt="" style=" object-fit: fit; height: 20rem;">
        </div>

        <div class="col-md-6 mb-4">
          <div class="p-4">
            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
            </div>

            <p class="">
              {% if object.discount_price %}
                <span class="mr-1">
                  <del>${{object.price}}</del>
                </span>
                <span>${{object.discount_price}}</span>
              {% else %}
                <span>${{object.price}}</span>
              {% endif %}
            </p>
            <p>Vendor: <a href="{% url 'vendor_detail' object.user.id %}"> {% firstof item.user.get_full_name item.user.username %} </a> </p>
            <p class="font-weight-bold">Description</p>

            <p>{{object.description}}</p>

              <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

              <a href="{{object.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p">
                Remove from cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </a>

          </div>
        </div>

      </div>

    </div>
{% endblock content %}
  

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}