base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('store.urls', namespace="store")),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

store/urls.py
from django.urls import path 
from .views import (CheckoutView, ItemDetail, HomeView, add_to_cart, 
                    remove_from_cart, OrderSummaryView, remove_single_item_from_cart,
                    PaymentView, AddCouponView, RequestRefundView, CategoryDetail
)
app_name = "store"

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("order-summary/", OrderSummaryView.as_view(), name="order-summary"),
    path("product/<slug>", ItemDetail.as_view(), name="product"),
    path("add-to-cart/<slug>", add_to_cart, name="add-to-cart"),
    path("add-coupon", AddCouponView.as_view(), name="add-coupon"),
    path("remove-from-cart/<slug>", remove_from_cart, name="remove-from-cart"),
    path("remove-single-item-from-cart/<slug>", remove_single_item_from_cart, name="remove-single-item-from-cart"),
    path("payment/<payment_option>", PaymentView.as_view(), name="payment"),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),

    path('categorydetail/<slug>', CategoryDetail, name='categorydetail')
]

templates/components/footer.html
<!-- Footer-->
<footer class="bg-dark pt-5 pb-3">
    <div class="container">
        <div class="row">
            <div class="footer-col">
                <h4 class="">company</h4>
                <ul>
                    <li><a href="#">about us</a></li>
                    <li><a href="#">our services</a></li>
                    <li><a href="#">privacy policy</a></li>
                    <li><a href="#">affiliate program</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>get help</h4>
                <ul>
                    <li><a href="#">FAQ</a></li>
                    <li><a href="#">shipping</a></li>
                    <li><a href="#">returns</a></li>
                    <li><a href="#">order status</a></li>
                    <li><a href="#">payment options</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>online shop</h4>
                <ul>
                    <li><a href="#">watch</a></li>
                    <li><a href="#">bag</a></li>
                    <li><a href="#">shoes</a></li>
                    <li><a href="#">dress</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>follow us</h4>
                <div class="social-links">
                    <a href="#"><i class="bi bi-facebook"></i></a>
                    <a href="#"><i class="bi bi-twitter"></i></a>
                    <a href="#"><i class="bi bi-instagram"></i></a>
                    <a href="#"><i class="bi bi-linkedin"></i></a>
                </div>
            </div>
        </div>
        <p class="mt-5 text-center text-white">Copyright &copy; Your Website 2022</p>
    </div>
</footer>

templates/components/header.html
{% load static %}

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'img/bg/back-img.jpg' %}" class="d-block w-100" alt="..." style="height: 85vh;">
      <div class="carousel-caption" style="top: 0; margin-top: 10rem;">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/bg/back-img2.jpg' %}" class="d-block w-100" alt="..." style="height: 85vh;">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="{% static 'img/bg/bg.jpg' %}" class="d-block w-100 img-fluid" alt="..." style="height: 85vh; object-fit: cover;">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

templates/components/menu.html
{% for category in categories %}
    <li><a href="{% url 'store:categorydetail' category.slug %}" class="dropdown-item" href="#">{{ category.title }}</a></li>
{% endfor %}

templates/components/navbar.html
{% load cart_template_tags %}
{% load menu %}

<nav
  class="navbar navbar-expand-lg navbar-light shadow-sm bg-light"
>
  <div class="container">
    <!-- Brand -->
    <a class="navbar-brand" href="/">
      <strong class="blue-text">STORE</strong>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Links -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left -->
      <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'store:home' %}">All Products</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Categories
              </a>
              <ul class="dropdown-menu">
                {% menu %}
              </ul>
          </li>
      </ul>


      <!-- Right -->

      <ul class="navbar-nav ms-auto">
        {% if request.user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'store:order-summary' %}" class="nav-link btn btn-outline-dark">
                <i class="bi-cart-fill me-1"></i>
                Cart
                <span class="badge bg-dark text-white ms-1 rounded-pill">{{request.user|cart_item_count}}</span>
            </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">
            <span class="clearfix d-sm-inline-block"> Logout </span>
          </a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">
            <span class="clearfix d-sm-inline-block"> Login </span>
          </a>
        </li>
        {% endif %}

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href='{% url "dashboard" %}'>My Dashboard</a>
        </li>
        {% endif %}


      </ul>

      

      

    </div>
  </div>
</nav>